// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.12.4
// source: doctor.proto

package doctor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WeekDay int32

const (
	WeekDay_MONDAY    WeekDay = 0
	WeekDay_TUESDAY   WeekDay = 1
	WeekDay_WEDNESDAY WeekDay = 2
	WeekDay_THURSDAY  WeekDay = 3
	WeekDay_FRIDAY    WeekDay = 4
	WeekDay_SATURDAY  WeekDay = 5
	WeekDay_SUNDAY    WeekDay = 6
)

// Enum value maps for WeekDay.
var (
	WeekDay_name = map[int32]string{
		0: "MONDAY",
		1: "TUESDAY",
		2: "WEDNESDAY",
		3: "THURSDAY",
		4: "FRIDAY",
		5: "SATURDAY",
		6: "SUNDAY",
	}
	WeekDay_value = map[string]int32{
		"MONDAY":    0,
		"TUESDAY":   1,
		"WEDNESDAY": 2,
		"THURSDAY":  3,
		"FRIDAY":    4,
		"SATURDAY":  5,
		"SUNDAY":    6,
	}
)

func (x WeekDay) Enum() *WeekDay {
	p := new(WeekDay)
	*p = x
	return p
}

func (x WeekDay) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WeekDay) Descriptor() protoreflect.EnumDescriptor {
	return file_doctor_proto_enumTypes[0].Descriptor()
}

func (WeekDay) Type() protoreflect.EnumType {
	return &file_doctor_proto_enumTypes[0]
}

func (x WeekDay) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WeekDay.Descriptor instead.
func (WeekDay) EnumDescriptor() ([]byte, []int) {
	return file_doctor_proto_rawDescGZIP(), []int{0}
}

type AvailableHour struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WeekDay   WeekDay `protobuf:"varint,1,opt,name=week_day,json=weekDay,proto3,enum=doctor.WeekDay" json:"week_day,omitempty"`
	StartHour int32   `protobuf:"varint,2,opt,name=start_hour,json=startHour,proto3" json:"start_hour,omitempty"`
	EndHour   int32   `protobuf:"varint,3,opt,name=end_hour,json=endHour,proto3" json:"end_hour,omitempty"`
}

func (x *AvailableHour) Reset() {
	*x = AvailableHour{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doctor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvailableHour) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailableHour) ProtoMessage() {}

func (x *AvailableHour) ProtoReflect() protoreflect.Message {
	mi := &file_doctor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailableHour.ProtoReflect.Descriptor instead.
func (*AvailableHour) Descriptor() ([]byte, []int) {
	return file_doctor_proto_rawDescGZIP(), []int{0}
}

func (x *AvailableHour) GetWeekDay() WeekDay {
	if x != nil {
		return x.WeekDay
	}
	return WeekDay_MONDAY
}

func (x *AvailableHour) GetStartHour() int32 {
	if x != nil {
		return x.StartHour
	}
	return 0
}

func (x *AvailableHour) GetEndHour() int32 {
	if x != nil {
		return x.EndHour
	}
	return 0
}

type Name struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstName  string `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	MiddleName string `protobuf:"bytes,2,opt,name=middle_name,json=middleName,proto3" json:"middle_name,omitempty"`
	LastName   string `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
}

func (x *Name) Reset() {
	*x = Name{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doctor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Name) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Name) ProtoMessage() {}

func (x *Name) ProtoReflect() protoreflect.Message {
	mi := &file_doctor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Name.ProtoReflect.Descriptor instead.
func (*Name) Descriptor() ([]byte, []int) {
	return file_doctor_proto_rawDescGZIP(), []int{1}
}

func (x *Name) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Name) GetMiddleName() string {
	if x != nil {
		return x.MiddleName
	}
	return ""
}

func (x *Name) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type Address struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Street     string `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City       string `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	State      string `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Country    string `protobuf:"bytes,4,opt,name=country,proto3" json:"country,omitempty"`
	PostalCode string `protobuf:"bytes,5,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
}

func (x *Address) Reset() {
	*x = Address{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doctor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_doctor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_doctor_proto_rawDescGZIP(), []int{2}
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Address) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

type Education struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Degree         string `protobuf:"bytes,1,opt,name=degree,proto3" json:"degree,omitempty"`
	University     string `protobuf:"bytes,2,opt,name=university,proto3" json:"university,omitempty"`
	GraduationYear int32  `protobuf:"varint,3,opt,name=graduation_year,json=graduationYear,proto3" json:"graduation_year,omitempty"`
}

func (x *Education) Reset() {
	*x = Education{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doctor_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Education) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Education) ProtoMessage() {}

func (x *Education) ProtoReflect() protoreflect.Message {
	mi := &file_doctor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Education.ProtoReflect.Descriptor instead.
func (*Education) Descriptor() ([]byte, []int) {
	return file_doctor_proto_rawDescGZIP(), []int{3}
}

func (x *Education) GetDegree() string {
	if x != nil {
		return x.Degree
	}
	return ""
}

func (x *Education) GetUniversity() string {
	if x != nil {
		return x.University
	}
	return ""
}

func (x *Education) GetGraduationYear() int32 {
	if x != nil {
		return x.GraduationYear
	}
	return 0
}

type ContactDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PhoneNumber      string `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Email            string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Website          string `protobuf:"bytes,3,opt,name=website,proto3" json:"website,omitempty"`
	EmergencyContact string `protobuf:"bytes,4,opt,name=emergency_contact,json=emergencyContact,proto3" json:"emergency_contact,omitempty"`
}

func (x *ContactDetails) Reset() {
	*x = ContactDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doctor_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContactDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactDetails) ProtoMessage() {}

func (x *ContactDetails) ProtoReflect() protoreflect.Message {
	mi := &file_doctor_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactDetails.ProtoReflect.Descriptor instead.
func (*ContactDetails) Descriptor() ([]byte, []int) {
	return file_doctor_proto_rawDescGZIP(), []int{4}
}

func (x *ContactDetails) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *ContactDetails) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ContactDetails) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *ContactDetails) GetEmergencyContact() string {
	if x != nil {
		return x.EmergencyContact
	}
	return ""
}

type Doctor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           *Name            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Specialty      string           `protobuf:"bytes,3,opt,name=specialty,proto3" json:"specialty,omitempty"`
	Educations     []*Education     `protobuf:"bytes,4,rep,name=educations,proto3" json:"educations,omitempty"`
	ContactDetails *ContactDetails  `protobuf:"bytes,5,opt,name=contact_details,json=contactDetails,proto3" json:"contact_details,omitempty"`
	AvailableHours []*AvailableHour `protobuf:"bytes,6,rep,name=available_hours,json=availableHours,proto3" json:"available_hours,omitempty"`
	Address        *Address         `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *Doctor) Reset() {
	*x = Doctor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doctor_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Doctor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Doctor) ProtoMessage() {}

func (x *Doctor) ProtoReflect() protoreflect.Message {
	mi := &file_doctor_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Doctor.ProtoReflect.Descriptor instead.
func (*Doctor) Descriptor() ([]byte, []int) {
	return file_doctor_proto_rawDescGZIP(), []int{5}
}

func (x *Doctor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Doctor) GetName() *Name {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *Doctor) GetSpecialty() string {
	if x != nil {
		return x.Specialty
	}
	return ""
}

func (x *Doctor) GetEducations() []*Education {
	if x != nil {
		return x.Educations
	}
	return nil
}

func (x *Doctor) GetContactDetails() *ContactDetails {
	if x != nil {
		return x.ContactDetails
	}
	return nil
}

func (x *Doctor) GetAvailableHours() []*AvailableHour {
	if x != nil {
		return x.AvailableHours
	}
	return nil
}

func (x *Doctor) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type RegisterDoctorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Doctor *Doctor `protobuf:"bytes,1,opt,name=doctor,proto3" json:"doctor,omitempty"`
}

func (x *RegisterDoctorRequest) Reset() {
	*x = RegisterDoctorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doctor_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterDoctorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDoctorRequest) ProtoMessage() {}

func (x *RegisterDoctorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_doctor_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDoctorRequest.ProtoReflect.Descriptor instead.
func (*RegisterDoctorRequest) Descriptor() ([]byte, []int) {
	return file_doctor_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterDoctorRequest) GetDoctor() *Doctor {
	if x != nil {
		return x.Doctor
	}
	return nil
}

type RegisterDoctorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DoctorId string `protobuf:"bytes,1,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
}

func (x *RegisterDoctorResponse) Reset() {
	*x = RegisterDoctorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doctor_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterDoctorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDoctorResponse) ProtoMessage() {}

func (x *RegisterDoctorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_doctor_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDoctorResponse.ProtoReflect.Descriptor instead.
func (*RegisterDoctorResponse) Descriptor() ([]byte, []int) {
	return file_doctor_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterDoctorResponse) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

type UpdateDoctorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DoctorId string  `protobuf:"bytes,1,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	Doctor   *Doctor `protobuf:"bytes,2,opt,name=doctor,proto3" json:"doctor,omitempty"`
}

func (x *UpdateDoctorRequest) Reset() {
	*x = UpdateDoctorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doctor_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDoctorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDoctorRequest) ProtoMessage() {}

func (x *UpdateDoctorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_doctor_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDoctorRequest.ProtoReflect.Descriptor instead.
func (*UpdateDoctorRequest) Descriptor() ([]byte, []int) {
	return file_doctor_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateDoctorRequest) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

func (x *UpdateDoctorRequest) GetDoctor() *Doctor {
	if x != nil {
		return x.Doctor
	}
	return nil
}

type UpdateDoctorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *UpdateDoctorResponse) Reset() {
	*x = UpdateDoctorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doctor_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateDoctorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDoctorResponse) ProtoMessage() {}

func (x *UpdateDoctorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_doctor_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDoctorResponse.ProtoReflect.Descriptor instead.
func (*UpdateDoctorResponse) Descriptor() ([]byte, []int) {
	return file_doctor_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateDoctorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// TODO:GT020 Add Filter Method for Doctors
type GetDoctorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DoctorId  string `protobuf:"bytes,1,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	ReturnAll bool   `protobuf:"varint,2,opt,name=return_all,json=returnAll,proto3" json:"return_all,omitempty"`
}

func (x *GetDoctorRequest) Reset() {
	*x = GetDoctorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doctor_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDoctorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDoctorRequest) ProtoMessage() {}

func (x *GetDoctorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_doctor_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDoctorRequest.ProtoReflect.Descriptor instead.
func (*GetDoctorRequest) Descriptor() ([]byte, []int) {
	return file_doctor_proto_rawDescGZIP(), []int{10}
}

func (x *GetDoctorRequest) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

func (x *GetDoctorRequest) GetReturnAll() bool {
	if x != nil {
		return x.ReturnAll
	}
	return false
}

type GetDoctorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Doctors []*Doctor `protobuf:"bytes,1,rep,name=doctors,proto3" json:"doctors,omitempty"`
}

func (x *GetDoctorResponse) Reset() {
	*x = GetDoctorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doctor_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDoctorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDoctorResponse) ProtoMessage() {}

func (x *GetDoctorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_doctor_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDoctorResponse.ProtoReflect.Descriptor instead.
func (*GetDoctorResponse) Descriptor() ([]byte, []int) {
	return file_doctor_proto_rawDescGZIP(), []int{11}
}

func (x *GetDoctorResponse) GetDoctors() []*Doctor {
	if x != nil {
		return x.Doctors
	}
	return nil
}

type DeleteDoctorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DoctorId string `protobuf:"bytes,1,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
}

func (x *DeleteDoctorRequest) Reset() {
	*x = DeleteDoctorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doctor_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDoctorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDoctorRequest) ProtoMessage() {}

func (x *DeleteDoctorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_doctor_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDoctorRequest.ProtoReflect.Descriptor instead.
func (*DeleteDoctorRequest) Descriptor() ([]byte, []int) {
	return file_doctor_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteDoctorRequest) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

type DeleteDoctorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *DeleteDoctorResponse) Reset() {
	*x = DeleteDoctorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doctor_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDoctorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDoctorResponse) ProtoMessage() {}

func (x *DeleteDoctorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_doctor_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDoctorResponse.ProtoReflect.Descriptor instead.
func (*DeleteDoctorResponse) Descriptor() ([]byte, []int) {
	return file_doctor_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteDoctorResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DoctorAvailabilityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DoctorId    string  `protobuf:"bytes,1,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	WeekDay     WeekDay `protobuf:"varint,2,opt,name=week_day,json=weekDay,proto3,enum=doctor.WeekDay" json:"week_day,omitempty"`
	CurrentHour int32   `protobuf:"varint,3,opt,name=current_hour,json=currentHour,proto3" json:"current_hour,omitempty"`
}

func (x *DoctorAvailabilityRequest) Reset() {
	*x = DoctorAvailabilityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doctor_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoctorAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorAvailabilityRequest) ProtoMessage() {}

func (x *DoctorAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_doctor_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*DoctorAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_doctor_proto_rawDescGZIP(), []int{14}
}

func (x *DoctorAvailabilityRequest) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

func (x *DoctorAvailabilityRequest) GetWeekDay() WeekDay {
	if x != nil {
		return x.WeekDay
	}
	return WeekDay_MONDAY
}

func (x *DoctorAvailabilityRequest) GetCurrentHour() int32 {
	if x != nil {
		return x.CurrentHour
	}
	return 0
}

type DoctorAvailabilityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Available bool `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
}

func (x *DoctorAvailabilityResponse) Reset() {
	*x = DoctorAvailabilityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_doctor_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoctorAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorAvailabilityResponse) ProtoMessage() {}

func (x *DoctorAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_doctor_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*DoctorAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_doctor_proto_rawDescGZIP(), []int{15}
}

func (x *DoctorAvailabilityResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

var File_doctor_proto protoreflect.FileDescriptor

var file_doctor_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x75, 0x0a, 0x0d, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61,
	0x62, 0x6c, 0x65, 0x48, 0x6f, 0x75, 0x72, 0x12, 0x2a, 0x0a, 0x08, 0x77, 0x65, 0x65, 0x6b, 0x5f,
	0x64, 0x61, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x64, 0x6f, 0x63, 0x74,
	0x6f, 0x72, 0x2e, 0x57, 0x65, 0x65, 0x6b, 0x44, 0x61, 0x79, 0x52, 0x07, 0x77, 0x65, 0x65, 0x6b,
	0x44, 0x61, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72, 0x74, 0x5f, 0x68, 0x6f, 0x75,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x48, 0x6f,
	0x75, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x5f, 0x68, 0x6f, 0x75, 0x72, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x48, 0x6f, 0x75, 0x72, 0x22, 0x63, 0x0a,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x69, 0x64, 0x64, 0x6c, 0x65, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x69, 0x64, 0x64, 0x6c,
	0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x4e, 0x61,
	0x6d, 0x65, 0x22, 0x86, 0x01, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x72, 0x65, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x73, 0x74, 0x72, 0x65, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6f,
	0x73, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x70, 0x6f, 0x73, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x6c, 0x0a, 0x09, 0x45,
	0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x67, 0x72,
	0x65, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x67, 0x72, 0x65, 0x65,
	0x12, 0x1e, 0x0a, 0x0a, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x79, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x69, 0x74, 0x79,
	0x12, 0x27, 0x0a, 0x0f, 0x67, 0x72, 0x61, 0x64, 0x75, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x79,
	0x65, 0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0e, 0x67, 0x72, 0x61, 0x64, 0x75,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x59, 0x65, 0x61, 0x72, 0x22, 0x90, 0x01, 0x0a, 0x0e, 0x43, 0x6f,
	0x6e, 0x74, 0x61, 0x63, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x21, 0x0a, 0x0c,
	0x70, 0x68, 0x6f, 0x6e, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x77, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x77, 0x65, 0x62, 0x73, 0x69, 0x74, 0x65, 0x12,
	0x2b, 0x0a, 0x11, 0x65, 0x6d, 0x65, 0x72, 0x67, 0x65, 0x6e, 0x63, 0x79, 0x5f, 0x63, 0x6f, 0x6e,
	0x74, 0x61, 0x63, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x65, 0x6d, 0x65, 0x72,
	0x67, 0x65, 0x6e, 0x63, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x22, 0xb7, 0x02, 0x0a,
	0x06, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x4e,
	0x61, 0x6d, 0x65, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x70, 0x65,
	0x63, 0x69, 0x61, 0x6c, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x70,
	0x65, 0x63, 0x69, 0x61, 0x6c, 0x74, 0x79, 0x12, 0x31, 0x0a, 0x0a, 0x65, 0x64, 0x75, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x64, 0x6f,
	0x63, 0x74, 0x6f, 0x72, 0x2e, 0x45, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0a,
	0x65, 0x64, 0x75, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x3f, 0x0a, 0x0f, 0x63, 0x6f,
	0x6e, 0x74, 0x61, 0x63, 0x74, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x43, 0x6f, 0x6e,
	0x74, 0x61, 0x63, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x52, 0x0e, 0x63, 0x6f, 0x6e,
	0x74, 0x61, 0x63, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x3e, 0x0a, 0x0f, 0x61,
	0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x68, 0x6f, 0x75, 0x72, 0x73, 0x18, 0x06,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x41, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x48, 0x6f, 0x75, 0x72, 0x52, 0x0e, 0x61, 0x76, 0x61,
	0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x12, 0x29, 0x0a, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x64,
	0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x3f, 0x0a, 0x15, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x26, 0x0a, 0x06, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x52,
	0x06, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x35, 0x0a, 0x16, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x22, 0x5a,
	0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72,
	0x49, 0x64, 0x12, 0x26, 0x0a, 0x06, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x6f, 0x63, 0x74,
	0x6f, 0x72, 0x52, 0x06, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x22, 0x30, 0x0a, 0x14, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x4e, 0x0a, 0x10,
	0x47, 0x65, 0x74, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x5f, 0x61, 0x6c, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x09, 0x72, 0x65, 0x74, 0x75, 0x72, 0x6e, 0x41, 0x6c, 0x6c, 0x22, 0x3d, 0x0a, 0x11,
	0x47, 0x65, 0x74, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x28, 0x0a, 0x07, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x6f, 0x63, 0x74,
	0x6f, 0x72, 0x52, 0x07, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x73, 0x22, 0x32, 0x0a, 0x13, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x22,
	0x30, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x22, 0x87, 0x01, 0x0a, 0x19, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x41, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x08,
	0x77, 0x65, 0x65, 0x6b, 0x5f, 0x64, 0x61, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f,
	0x2e, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x57, 0x65, 0x65, 0x6b, 0x44, 0x61, 0x79, 0x52,
	0x07, 0x77, 0x65, 0x65, 0x6b, 0x44, 0x61, 0x79, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x74, 0x5f, 0x68, 0x6f, 0x75, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b,
	0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x48, 0x6f, 0x75, 0x72, 0x22, 0x3a, 0x0a, 0x1a, 0x44,
	0x6f, 0x63, 0x74, 0x6f, 0x72, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x76, 0x61,
	0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x61, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x2a, 0x65, 0x0a, 0x07, 0x57, 0x65, 0x65, 0x6b, 0x44,
	0x61, 0x79, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x4f, 0x4e, 0x44, 0x41, 0x59, 0x10, 0x00, 0x12, 0x0b,
	0x0a, 0x07, 0x54, 0x55, 0x45, 0x53, 0x44, 0x41, 0x59, 0x10, 0x01, 0x12, 0x0d, 0x0a, 0x09, 0x57,
	0x45, 0x44, 0x4e, 0x45, 0x53, 0x44, 0x41, 0x59, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x54, 0x48,
	0x55, 0x52, 0x53, 0x44, 0x41, 0x59, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x52, 0x49, 0x44,
	0x41, 0x59, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x41, 0x54, 0x55, 0x52, 0x44, 0x41, 0x59,
	0x10, 0x05, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x55, 0x4e, 0x44, 0x41, 0x59, 0x10, 0x06, 0x32, 0x9a,
	0x03, 0x0a, 0x0d, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x4f, 0x0a, 0x0e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x44, 0x6f, 0x63, 0x74,
	0x6f, 0x72, 0x12, 0x1d, 0x2e, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1e, 0x2e, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73,
	0x74, 0x65, 0x72, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x40, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x18,
	0x2e, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x63, 0x74, 0x6f,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x64, 0x6f, 0x63, 0x74, 0x6f,
	0x72, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x60, 0x0a, 0x17, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x44, 0x6f, 0x63, 0x74,
	0x6f, 0x72, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x21,
	0x2e, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x41, 0x76,
	0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x22, 0x2e, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x6f, 0x63, 0x74, 0x6f,
	0x72, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x44,
	0x6f, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x1b, 0x2e, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x49, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72,
	0x12, 0x1b, 0x2e, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e,
	0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x6f, 0x63,
	0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x2d, 0x5a, 0x2b, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x74, 0x68, 0x65, 0x2d, 0x73, 0x70,
	0x69, 0x6e, 0x65, 0x2f, 0x73, 0x70, 0x69, 0x6e, 0x65, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2d, 0x67, 0x6f, 0x2f, 0x64, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_doctor_proto_rawDescOnce sync.Once
	file_doctor_proto_rawDescData = file_doctor_proto_rawDesc
)

func file_doctor_proto_rawDescGZIP() []byte {
	file_doctor_proto_rawDescOnce.Do(func() {
		file_doctor_proto_rawDescData = protoimpl.X.CompressGZIP(file_doctor_proto_rawDescData)
	})
	return file_doctor_proto_rawDescData
}

var file_doctor_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_doctor_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_doctor_proto_goTypes = []interface{}{
	(WeekDay)(0),                       // 0: doctor.WeekDay
	(*AvailableHour)(nil),              // 1: doctor.AvailableHour
	(*Name)(nil),                       // 2: doctor.Name
	(*Address)(nil),                    // 3: doctor.Address
	(*Education)(nil),                  // 4: doctor.Education
	(*ContactDetails)(nil),             // 5: doctor.ContactDetails
	(*Doctor)(nil),                     // 6: doctor.Doctor
	(*RegisterDoctorRequest)(nil),      // 7: doctor.RegisterDoctorRequest
	(*RegisterDoctorResponse)(nil),     // 8: doctor.RegisterDoctorResponse
	(*UpdateDoctorRequest)(nil),        // 9: doctor.UpdateDoctorRequest
	(*UpdateDoctorResponse)(nil),       // 10: doctor.UpdateDoctorResponse
	(*GetDoctorRequest)(nil),           // 11: doctor.GetDoctorRequest
	(*GetDoctorResponse)(nil),          // 12: doctor.GetDoctorResponse
	(*DeleteDoctorRequest)(nil),        // 13: doctor.DeleteDoctorRequest
	(*DeleteDoctorResponse)(nil),       // 14: doctor.DeleteDoctorResponse
	(*DoctorAvailabilityRequest)(nil),  // 15: doctor.DoctorAvailabilityRequest
	(*DoctorAvailabilityResponse)(nil), // 16: doctor.DoctorAvailabilityResponse
}
var file_doctor_proto_depIdxs = []int32{
	0,  // 0: doctor.AvailableHour.week_day:type_name -> doctor.WeekDay
	2,  // 1: doctor.Doctor.name:type_name -> doctor.Name
	4,  // 2: doctor.Doctor.educations:type_name -> doctor.Education
	5,  // 3: doctor.Doctor.contact_details:type_name -> doctor.ContactDetails
	1,  // 4: doctor.Doctor.available_hours:type_name -> doctor.AvailableHour
	3,  // 5: doctor.Doctor.address:type_name -> doctor.Address
	6,  // 6: doctor.RegisterDoctorRequest.doctor:type_name -> doctor.Doctor
	6,  // 7: doctor.UpdateDoctorRequest.doctor:type_name -> doctor.Doctor
	6,  // 8: doctor.GetDoctorResponse.doctors:type_name -> doctor.Doctor
	0,  // 9: doctor.DoctorAvailabilityRequest.week_day:type_name -> doctor.WeekDay
	7,  // 10: doctor.DoctorService.RegisterDoctor:input_type -> doctor.RegisterDoctorRequest
	11, // 11: doctor.DoctorService.GetDoctor:input_type -> doctor.GetDoctorRequest
	15, // 12: doctor.DoctorService.CheckDoctorAvailability:input_type -> doctor.DoctorAvailabilityRequest
	9,  // 13: doctor.DoctorService.UpdateDoctor:input_type -> doctor.UpdateDoctorRequest
	13, // 14: doctor.DoctorService.DeleteDoctor:input_type -> doctor.DeleteDoctorRequest
	8,  // 15: doctor.DoctorService.RegisterDoctor:output_type -> doctor.RegisterDoctorResponse
	12, // 16: doctor.DoctorService.GetDoctor:output_type -> doctor.GetDoctorResponse
	16, // 17: doctor.DoctorService.CheckDoctorAvailability:output_type -> doctor.DoctorAvailabilityResponse
	10, // 18: doctor.DoctorService.UpdateDoctor:output_type -> doctor.UpdateDoctorResponse
	14, // 19: doctor.DoctorService.DeleteDoctor:output_type -> doctor.DeleteDoctorResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_doctor_proto_init() }
func file_doctor_proto_init() {
	if File_doctor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_doctor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvailableHour); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doctor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Name); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doctor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Address); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doctor_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Education); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doctor_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContactDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doctor_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Doctor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doctor_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterDoctorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doctor_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterDoctorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doctor_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDoctorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doctor_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateDoctorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doctor_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDoctorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doctor_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDoctorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doctor_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDoctorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doctor_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDoctorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doctor_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoctorAvailabilityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_doctor_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoctorAvailabilityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_doctor_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_doctor_proto_goTypes,
		DependencyIndexes: file_doctor_proto_depIdxs,
		EnumInfos:         file_doctor_proto_enumTypes,
		MessageInfos:      file_doctor_proto_msgTypes,
	}.Build()
	File_doctor_proto = out.File
	file_doctor_proto_rawDesc = nil
	file_doctor_proto_goTypes = nil
	file_doctor_proto_depIdxs = nil
}
